### ISSUE TITLE
请问5.x版本的user-guide在哪里看呢？

### ISSUE THREAD

**Issue by ghost** [waylau/activiti-5.x-user-guide#2]
官方最新版更新到了6.0了，跟楼主写的内容有些不一样，而且，最重要的是，每一章的阅读顺序楼主没有给出来，只能参考官方的文档看。。。

**Comment by waylau** [comment]
@binarySortTree   有目录  https://github.com/waylau/activiti-5.x-user-guide/blob/master/SUMMARY.md
